# 发布

name: Go Release

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
  
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.23

      - name: Build
        run: |
          make -j4 all

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
          token: ${{ secrets.GITHUB_TOKEN }}
          repo: ${{ github.repository }}
          tag: ${{ github.ref }}
          title: ${{ github.ref }}
          body: ${{ github.ref }}
