# 测试用例

name: Go Test

on:
  push:
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.23

    - name: Run tests
      run: go test -v ./...

    - name: Test
      uses: robherley/go-test-action@v0